### ISSUE TITLE
Error happened when changing build-in dataset into my own

### ISSUE THREAD

**Issue by huanghjA** [awslabs/dgl-ke#135]
Firstly, run the following command and successfully done
`dglke_train --model_name TransE_l1 --dataset FB15k ......` 

Since FB15k has existed, I want to train directly without downloading. Then, I change the `--dataset FB15k` into:
`dglke_train --model_name TransE_l1 --data_path ./data/FB15k/ --data_files entities.dict relations.dict train.txt valid.txt test.txt --format udd_hrt .....`

However, the terminal gives me an error:
```
Using backend: pytorch
Traceback (most recent call last):
  File "/home/hjhuang/anaconda3/envs/dgl/bin/dglke_train", line 33, in <module>
    sys.exit(load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')())
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/train.py", line 81, in main
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/dataloader/KGDataset.py", line 603, in get_dataset
AssertionError: You should provide the dataset name for raw_udd format.
```

**Comment by classicsong** [comment]
You should give a name to your dataset using `--dataset xxx`

**Comment by huanghjA** [comment]
Thank you for replying and it works.
However, another error happened and the input file format was built-in FB15k without edit.
```
Using backend: pytorch
Reading train triples....
For User Defined Dataset, both node ids and relation ids in the triplets should be int other than /m/027rn      /location/country/form_of_government    /m/06cx9
Traceback (most recent call last):
  File "/home/hjhuang/anaconda3/envs/dgl/bin/dglke_train", line 33, in <module>
    sys.exit(load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')())
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/train.py", line 81, in main
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/dataloader/KGDataset.py", line 610, in get_dataset
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/dataloader/KGDataset.py", line 526, in __init__
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/dataloader/KGDataset.py", line 92, in __init__
  File "/home/hjhuang/anaconda3/envs/dgl/lib/python3.6/site-packages/dglke-0.1.0.dev0-py3.6.egg/dglke/dataloader/KGDataset.py", line 556, in read_triple
ValueError: invalid literal for int() with base 10: '/m/027rn'
```

**Comment by huanghjA** [comment]
Thank you for replying and it works!

**Comment by classicsong** [comment]
Thanks for using DGL-KE

**Comment by Ashutosh2407** [comment]
Even I am trying to do the same on Freebase but I am getting this error:
Traceback (most recent call last):
  File "/home/ashutosh/anaconda3/envs/dgl_pytorch/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/ashutosh/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/train.py", line 92, in main
    dataset = get_dataset(args.data_path, args.dataset, args.format, args.data_files)
  File "/home/ashutosh/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 522, in get_dataset
    dataset = KGDatasetUDD(data_path, data_name, files, format)
  File "/home/ashutosh/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 446, in __init__
    assert os.path.exists(os.path.join(path, f)), \
AssertionError: File [entity2id.txt now exist in /my_task/data/Freebase

**Comment by classicsong** [comment]
You should check if entity2id.txt exists under /my_task/data/Freebase

**Comment by Ashutosh2407** [comment]
Yes it does.
I trained TransE model on freebase.So at first it downloaded freebase automatically.It is located at /my_task/data/Freebase.
Now I want to train another model on Freebase but since it is already present at  /my_task/data/Freebase I dont want to download again.So ,I created another folder under root named my_task_transe and I am trying to train in that folder.This was my command to read train,entity,relation file from another folder:

dglke_train --model_name TransE --dataset Freebase --data_path ./my_task/data/Freebase/ --format udd_{htr} --data_files [entity2id.txt relation2id.txt train.txt] --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 10 --lr 0.1 --regularization_coef 1e-9 --batch_size_eval 1000 --test -adv --mix_cpu_gpu --num_proc 8 --num_thread 4 --gpu 0 1  --max_step 320000 --neg_sample_size_eval 1000 --log_interval 1000 --async_update --rel_part --force_sync_interval 10000

**Comment by classicsong** [comment]
Can you try:
```
dglke_train --model_name TransE --dataset Freebase --data_path ./my_task/data/Freebase/ --format udd_hrt --data_files entity2id.txt relation2id.txt train.txt --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 10 --lr 0.1 --regularization_coef 1e-9 --batch_size_eval 1000 --test -adv --mix_cpu_gpu --num_proc 8 --num_thread 4 --gpu 0 1 --max_step 320000 --neg_sample_size_eval 1000 --log_interval 1000 --async_update --rel_part --force_sync_interval 10000
```
BTW --data_path should be ./my_task/data/Freebase/ or /my_task/data/Freebase/?

**Comment by nasimshm** [comment]
Hello, I have three files for train, valid, and test in the format of "htr" in **IDs**. Also two files to map the IDs to entities or relations. I am using Freebase. I just used the following command **BUT** I receive both errors ("AssertionError: You should provide the dataset name for udd format" , and "AssertionError: File id2entity.txt not exist in ./home/nasim/FB/".
Could you please help me?

My command: 
CUDA_VISIBLE_DEVICES=0,1 nohup dglke_train --model_name TransE_l2 --dataset Freebase --data_path ./home/nasim/FB/ --format udd_htr  --data_files id2entity.txt id2relation.txt train.txt valid.txt test.txt --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 10 --lr 0.1 --regularization_coef 1e-9 --batch_size_eval 1000 --test -adv --mix_cpu_gpu --num_proc 8 --num_thread 4 --gpu 0 1  --max_step 320000 --neg_sample_size_eval 1000 --log_interval 1000 --async_update --rel_part --force_sync_interval 10000 --no_save_em &

The errors: 
Traceback (most recent call last):
  File "/home/nasim/anaconda3/envs/dgl_pytorch/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/train.py", line 81, in main
    dataset = get_dataset(args.data_path,
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 652, in get_dataset
    assert data_name != 'FB15k', 'You should provide the dataset name for udd format.'
**AssertionError: You should provide the dataset name for udd format.**
Reading train triples....
Traceback (most recent call last):
  File "/home/nasim/anaconda3/envs/dgl_pytorch/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/train.py", line 81, in main
    dataset = get_dataset(args.data_path,
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 654, in get_dataset
    dataset = KGDatasetUDD(data_path, data_name, delimiter, files, format, has_edge_importance)
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 556, in __init__
    super(KGDatasetUDD, self).__init__(os.path.join(path, files[0]),
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 92, in __init__
    self.train = self.read_triple(train_path, "train", skip_first_line, format)
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 591, in read_triple
    h, r, t = triple[format[0]], triple[format[1]], triple[format[2]]
**TypeError: 'NoneType' object is not subscriptable**
Reading train triples....
Traceback (most recent call last):
  File "/home/nasim/anaconda3/envs/dgl_pytorch/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/train.py", line 81, in main
    dataset = get_dataset(args.data_path,
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 654, in get_dataset
    dataset = KGDatasetUDD(data_path, data_name, delimiter, files, format, has_edge_importance)
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 556, in __init__
    super(KGDatasetUDD, self).__init__(os.path.join(path, files[0]),
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 92, in __init__
    self.train = self.read_triple(train_path, "train", skip_first_line, format)
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 591, in read_triple
    h, r, t = triple[format[0]], triple[format[1]], triple[format[2]]
**TypeError: 'NoneType' object is not subscriptable**
Traceback (most recent call last):
  File "/home/nasim/anaconda3/envs/dgl_pytorch/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/train.py", line 81, in main
    dataset = get_dataset(args.data_path,
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 654, in get_dataset
    dataset = KGDatasetUDD(data_path, data_name, delimiter, files, format, has_edge_importance)
  File "/home/nasim/anaconda3/envs/dgl_pytorch/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 536, in __init__
    assert os.path.exists(os.path.join(path, f)), \
**AssertionError: File id2entity.txt not exist in ./home/nasim/FB/**
