### ISSUE TITLE
Can't run default distributed example

### ISSUE THREAD

**Issue by shriphani** [awslabs/dgl-ke#181]
Hi, I'm unable to run the exact FB15k distributed example on my cluster using the exact same parameters as the example (with the IPs changed).

It seems to be unable to parse the ip_config file (which is actually alright since it does copy the script to the remote machines correctly) but complains later about the format.

And then I get: `AttributeError: 'Namespace' object has no attribute 'has_edge_importance'` which isn't an argument to the dglke_dist_train command.

I am on Ubuntu 20.04, Python 3.8 and dglke / dgl installed as the instructions suggest.

Full error below:

```
onu@squidroost1:~$ dglke_dist_train --path ~/my_task --ip_config ~/my_task/ip_config.txt \
> --num_client_proc 16 --model_name TransE_l2 --dataset FB15k --data_path ~/my_task --hidden_dim 400 \
> --gamma 19.9 --lr 0.25 --batch_size 1000 --neg_sample_size 200 --max_step 500 --log_interval 100 \
> --batch_size_eval 16 --test -adv --regularization_coef 1.00E-09 --num_thread 1
Copy script to remote machine ...
dglke_start_kvserver_kvclient.sh                                                                    100%  975   847.0KB/s   00:00    
dglke_start_kvserver_kvclient.sh                                                                    100%  975     1.3MB/s   00:00    
dglke_start_kvserver_kvclient.sh                                                                    100%  975     1.2MB/s   00:00    
ssh 192.168.1.123 'cd /home/onu/my_task; ./dglke_start_kvserver_kvclient.sh 8 16'
ssh 192.168.1.124 'cd /home/onu/my_task; ./dglke_start_kvserver_kvclient.sh 16 24'
ssh 192.168.1.125 'cd /home/onu/my_task; ./dglke_start_kvserver_kvclient.sh 24 32'
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
n_entities: 10579
n_relations: 1345
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 19
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 159, in start_server
    g2l, entity_emb, entity_emb_state, relation_emb, relation_emb_state = get_server_data(args, my_server.get_machine_id())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 120, in get_server_data
    model = load_model(args, dataset.n_entities, dataset.n_relations)
  File "/usr/local/lib/python3.8/dist-packages/dglke/train_pytorch.py", line 98, in load_model
    model = KEModel(args, args.model_name, n_entities, n_relations,
  File "/usr/local/lib/python3.8/dist-packages/dglke/models/general_models.py", line 203, in __init__
    self.has_edge_importance = args.has_edge_importance
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 25
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 20
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 22
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 18
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 29
Error: data format on each line should be: [ip] [base_port] [server_count]
n_entities: 7774
n_relations: 1345
/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvserver.py:133: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvserver.py:133: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 28
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 27
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 11, in <module>
    load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_server')()
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvserver.py", line 178, in main
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvserver.py", line 159, in start_server
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvserver.py", line 120, in get_server_data
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/train_pytorch.py", line 98, in load_model
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/models/general_models.py", line 212, in __init__
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Error: data format on each line should be: [ip] [base_port] [server_count]
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 31
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 24
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 21
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 16
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 26
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 17
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 30
Traceback (most recent call last):
  File "/usr/local/bin/dglke_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 178, in main
    start_server(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvserver.py", line 147, in start_server
    port = server_namebook[args.server_id][2]
KeyError: 23
Error: data format on each line should be: [ip] [base_port] [server_count]
Reading train triples....
Finished. Read 116786 train triples.
Partition 0 n_entities: 10579
Partition 0 n_relations: 1345
|Train|: 116786
random partition 116786 edges into 16 parts
part 0 has 7300 edges
part 1 has 7300 edges
part 2 has 7300 edges
part 3 has 7300 edges
part 4 has 7300 edges
part 5 has 7300 edges
part 6 has 7300 edges
part 7 has 7300 edges
part 8 has 7300 edges
part 9 has 7300 edges
part 10 has 7300 edges
part 11 has 7300 edges
part 12 has 7300 edges
part 13 has 7300 edges
part 14 has 7300 edges
part 15 has 7286 edges
Traceback (most recent call last):
  File "/usr/local/bin/dglke_client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 209, in main
    start_client(args)   
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 150, in start_client
    train_data = TrainDataset(dataset, args, ranks=args.num_client)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 343, in __init__
    self.g = ConstructGraph(triples, dataset.n_entities, args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 304, in ConstructGraph
    if args.has_edge_importance:
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
Error: data format on each line should be: [ip] [base_port] [server_count]
Reading train triples....
Finished. Read 116786 train triples.
Partition 0 n_entities: 10579
Partition 0 n_relations: 1345
|Train|: 116786
random partition 116786 edges into 16 parts
part 0 has 7300 edges
part 1 has 7300 edges
part 2 has 7300 edges
part 3 has 7300 edges
part 4 has 7300 edges
part 5 has 7300 edges
part 6 has 7300 edges
part 7 has 7300 edges
part 8 has 7300 edges
part 9 has 7300 edges
part 10 has 7300 edges
part 11 has 7300 edges
part 12 has 7300 edges
part 13 has 7300 edges
part 14 has 7300 edges
part 15 has 7286 edges
Traceback (most recent call last):
  File "/usr/local/bin/dglke_client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 209, in main
    start_client(args)   
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 150, in start_client
    train_data = TrainDataset(dataset, args, ranks=args.num_client)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 343, in __init__
    self.g = ConstructGraph(triples, dataset.n_entities, args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 304, in ConstructGraph
    if args.has_edge_importance:
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
Traceback (most recent call last):
  File "/usr/local/bin/dglke_dist_train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/dist_train.py", line 202, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dist_train.py", line 198, in launch
    wait_job(job_list[i], cmd_list[i])
  File "/usr/local/lib/python3.8/dist-packages/dglke/dist_train.py", line 89, in wait_job
    raise RuntimeError(mesg)
RuntimeError: Fail with retcode(1): cd /home/onu/my_task; ./dglke_start_kvserver_kvclient.sh 0 8
Error: data format on each line should be: [ip] [base_port] [server_count]
Reading train triples....
Finished. Read 93084 train triples.
Partition 1 n_entities: 7774
Partition 1 n_relations: 1345
|Train|: 93084
random partition 93084 edges into 16 parts
part 0 has 5818 edges
part 1 has 5818 edges
part 2 has 5818 edges
part 3 has 5818 edges
part 4 has 5818 edges
part 5 has 5818 edges
part 6 has 5818 edges
part 7 has 5818 edges
part 8 has 5818 edges
part 9 has 5818 edges
part 10 has 5818 edges
part 11 has 5818 edges
part 12 has 5818 edges
part 13 has 5818 edges
part 14 has 5818 edges
part 15 has 5814 edges
onu@squidroost1:~$ Traceback (most recent call last):
  File "/usr/local/bin/dglke_client", line 11, in <module>
    load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_client')()
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvclient.py", line 209, in main
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/kvclient.py", line 150, in start_client
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/dataloader/sampler.py", line 343, in __init__
  File "/usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg/dglke/dataloader/sampler.py", line 304, in ConstructGraph
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
Error: data format on each line should be: [ip] [base_port] [server_count]
Reading train triples....
Finished. Read 116786 train triples.
Partition 0 n_entities: 10579
Partition 0 n_relations: 1345
|Train|: 116786
random partition 116786 edges into 16 parts
part 0 has 7300 edges
part 1 has 7300 edges
part 2 has 7300 edges
part 3 has 7300 edges
part 4 has 7300 edges
part 5 has 7300 edges
part 6 has 7300 edges
part 7 has 7300 edges
part 8 has 7300 edges
part 9 has 7300 edges
part 10 has 7300 edges
part 11 has 7300 edges
part 12 has 7300 edges
part 13 has 7300 edges
part 14 has 7300 edges
part 15 has 7286 edges
Traceback (most recent call last):
  File "/usr/local/bin/dglke_client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 209, in main
    start_client(args)   
  File "/usr/local/lib/python3.8/dist-packages/dglke/kvclient.py", line 150, in start_client
    train_data = TrainDataset(dataset, args, ranks=args.num_client)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 343, in __init__
    self.g = ConstructGraph(triples, dataset.n_entities, args)
  File "/usr/local/lib/python3.8/dist-packages/dglke/dataloader/sampler.py", line 304, in ConstructGraph
    if args.has_edge_importance:
AttributeError: 'Namespace' object has no attribute 'has_edge_importance'
```

Any help would be appreciated.

**Comment by shriphani** [comment]
A small update. I had a trailing whitespace in my ip_config.txt. But the `AttributeError: 'Namespace' object has no attribute 'has_edge_importance'` still keeps appearing. Any ideas what is going on?

**Comment by classicsong** [comment]
Are you using master or any pip install version?

**Comment by shriphani** [comment]
Pip install for both dgl and dglke:

```
sudo pip3 install dgl==0.4.3
sudo pip3 install dglke
```

**Comment by shriphani** [comment]
And this is what I see:

```
onu@squidroost2:~$ sudo pip3 install dglke
[sudo] password for onu:
Requirement already satisfied: dglke in /usr/local/lib/python3.8/dist-packages/dglke-0.1.0.dev0-py3.8.egg (0.1.0.dev0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from dglke) (1.20.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from dglke) (45.2.0)
onu@squidroost2:~$
```

maybe the 0.1.0.dev0 is the problem?

**Comment by classicsong** [comment]
Please try v0.1.0

**Comment by shriphani** [comment]
No luck unfortunately. It does make some more progress but this error still appears. I've attached a link to the full log file:

https://gist.github.com/shriphani/f6e94b1fc717edd8568e68e1b36e239b

All 4 instances are running dglke==0.1.0 from pip.

**Comment by classicsong** [comment]
The error is due to the new argument args.has_edge_importance, which is not introduced until 0.1.1 release. 
Can you double check the dglke package version on all your distributed instances?

**Comment by shriphani** [comment]
Pasting the versions on all my instances: (they seem to all be 0.1.0).

```
onu@squidroost1:~$ sudo pip3 install dglke
[sudo] password for onu:
Requirement already satisfied: dglke in /usr/local/lib/python3.8/dist-packages (0.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from dglke) (1.20.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from dglke) (45.2.0)
```

```
onu@squidroost2:~$ sudo pip3 install dglke
[sudo] password for onu:
Requirement already satisfied: dglke in /usr/local/lib/python3.8/dist-packages (0.1.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from dglke) (45.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from dglke) (1.20.1)
```

```
onu@squidroost8:~$ sudo pip3 install dglke
[sudo] password for onu:
Requirement already satisfied: dglke in /usr/local/lib/python3.8/dist-packages (0.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from dglke) (1.20.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from dglke) (45.2.0)
```

```
onu@squidroost7:~$ sudo pip3 install dglke
[sudo] password for onu:
Requirement already satisfied: dglke in /usr/local/lib/python3.8/dist-packages (0.1.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from dglke) (45.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from dglke) (1.20.1)
```

**Comment by classicsong** [comment]
Oops. You are using python 3.8.
Someone else report a compatibility bug of kge with 3.8. Can you try 3.6 or 3.7?
Not sure if this cause the problem.

BTW, can you try single machine run?

**Comment by shriphani** [comment]
Single core works perfectly fine: https://gist.github.com/shriphani/1c2d3bf51d79b9ae93125457dec1fb6e

**Comment by shriphani** [comment]
Ok I wiped the full set of libraries installed by pip, installed dglke with the command `sudo pip3 install --no-cache-dir dglke==0.1.0` and the error still doesn't go away on python 3.8. 

I am going to try dropping the version to 3.6 and seeing if it works.

**Comment by shriphani** [comment]
Ok I figured it out. I did an install from the git repo a while back and that was appearing earlier in the $PYTHONPATH than the one from PyPi. Removed it and it works fine.

Thank you for all the help. I'm going to close the issue now.
