### ISSUE TITLE
AssertionError: Unknown dataset three_all

### ISSUE THREAD

**Issue by Su-hong-yu** [awslabs/dgl-ke#243]
### `suhongyu@su:~/my_task$ dglke_train --model_name TransE_l2 --data_path /home/suhongyu/my_task/data/three_all --dataset three_all --data_files train.txt valid.txt test.txt \
Traceback (most recent call last):
  File "/home/suhongyu/anaconda3/envs/openke/bin/dglke_train", line 8, in <module>
    sys.exit(main())
  File "/home/suhongyu/anaconda3/envs/openke/lib/python3.8/site-packages/dglke/train.py", line 81, in main
    dataset = get_dataset(args.data_path,
  File "/home/suhongyu/anaconda3/envs/openke/lib/python3.8/site-packages/dglke/dataloader/KGDataset.py", line 644, in get_dataset
    assert False, "Unknown dataset {}".format(data_name)
AssertionError: Unknown dataset three_all `

what shoud I do to solve this problem?

**Comment by zahramahani** [comment]
hi i found problem according to your address of error 
you need to define format for your data so add this:
--format raw_udd_htr
or 
--format  udd_htr

to learn more check documention:
[dgl_doc](https://dglke.dgl.ai/doc/train.html)
