### ISSUE TITLE
can't train my KG ,it keeps telling me 'AssertionError: test set is not provided'

### ISSUE THREAD

**Issue by Master000Munetani** [awslabs/dgl-ke#276]
**got the words following,help!!!.**
> $ dglke_train --model_name TransE --data_path /work/home/zqy_hzau/lys/dgl_tool/test02/raw_KG_data/up001 --dataset up001 --format raw_udd_hrt --data_files train.txt --delimiter , --batch_size 1000 --neg_sample_size 200 --hidden_dim 400 --gamma 19.9 --lr 0.25 --max_step 500 --log_interval 100 --batch_size_eval 16 -adv --regularization_coef 1.00E-09 --test --num_thread 1 --num_proc 8
Reading train triples....
Finished. Read 4744 train triples.
/work/home/zqy_hzau/anaconda3/envs/pytorch_lys/lib/python3.9/site-packages/dgl/_deprecate/graph.py:1023: DGLWarning: multigraph will be deprecated.DGL will treat all graphs as multigraph in the future.
  dgl_warning("multigraph will be deprecated." \
|Train|: 4744
random partition 4744 edges into 8 parts
part 0 has 593 edges
part 1 has 593 edges
part 2 has 593 edges
part 3 has 593 edges
part 4 has 593 edges
part 5 has 593 edges
part 6 has 593 edges
part 7 has 593 edges
Traceback (most recent call last):
  File "/work/home/zqy_hzau/anaconda3/envs/pytorch_lys/bin/dglke_train", line 33, in <module>
    sys.exit(load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')())
  File "/work/home/zqy_hzau/anaconda3/envs/pytorch_lys/lib/python3.9/site-packages/dglke-0.1.0.dev0-py3.9.egg/dglke/train.py", line 178, in main
AssertionError: test set is not provided

**Comment by classicsong** [comment]
Have you provided a test set?
