### ISSUE TITLE
Setup-issue-Windows-10

### ISSUE THREAD

**Issue by rizwan29** [awslabs/dgl-ke#90]
Environment:
Windows -10 (only CPU)
torch: 1.5.0
dgl: 0.4.3
dgl-ke: built from source code.

Encountered below error while trying to execute a command given in the tutorial.

dglke_train --model_name TransE_l2 --dataset FB15k --batch_size 1000 \
--neg_sample_size 200 --hidden_dim 400 --gamma 19.9 --lr 0.25 --max_step 500 --log_interval 100 \
--batch_size_eval 16 -adv --regularization_coef 1.00E-09 --test --num_thread 1 --num_proc 8

Logs are being recorded at: ckpts\TransE_l2_FB15k_3\train.log
Reading train triples....
Finished. Read 483142 train triples.
Reading valid triples....
Finished. Read 50000 valid triples.
Reading test triples....
Finished. Read 59071 test triples.
|Train|: 483142
random partition 483142 edges into 8 parts
part 0 has 60393 edges
part 1 has 60393 edges
part 2 has 60393 edges
part 3 has 60393 edges
part 4 has 60393 edges
part 5 has 60393 edges
part 6 has 60393 edges
part 7 has 60391 edges

Using backend: pytorch
C:\Users\riz\Anaconda3\lib\site-packages\dgl\base.py:25: UserWarning: multigraph will be deprecated.DGL will treat all graphs as multigraph in the future.
  warnings.warn(msg, warn_type)
Traceback (most recent call last):
  File "C:\Users\riz\Anaconda3\Scripts\dglke_train-script.py", line 11, in <module>
    load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')()
  File "C:\Users\riz\Anaconda3\lib\site-packages\dglke-0.1.0.dev0-py3.7.egg\dglke\train.py", line 129, in main
  File "C:\Users\riz\Anaconda3\lib\site-packages\dglke-0.1.0.dev0-py3.7.egg\dglke\dataloader\sampler.py", line 368, in create_sampler
  File "C:\Users\riz\Anaconda3\lib\site-packages\dgl\contrib\sampling\sampler.py", line 660, in __init__
    self._seed_edges = utils.toindex(self._seed_edges)
  File "C:\Users\riz\Anaconda3\lib\site-packages\dgl\utils.py", line 242, in toindex
    return data if isinstance(data, Index) else Index(data)
  File "C:\Users\riz\Anaconda3\lib\site-packages\dgl\utils.py", line 15, in __init__
    self._initialize_data(data)
  File "C:\Users\riz\Anaconda3\lib\site-packages\dgl\utils.py", line 22, in _initialize_data
    self._dispatch(data)
  File "C:\Users\riz\Anaconda3\lib\site-packages\dgl\utils.py", line 47, in _dispatch
    raise DGLError('Index data must be an int64 vector, but got: %s' % str(data))
dgl._ffi.base.DGLError: Index data must be an int64 vector, but got: tensor([ 68037, 423679, 381929,  ..., 440877,  26144, 464339],
       dtype=torch.int32)

I am not sure whether it's a bug or I missed something in the setup. Can someone please help me to resolve this?

**Comment by zheng-da** [comment]
This is probably a bug in DGL. We didn't test it in Windows.

**Comment by rizwan29** [comment]
thanks @zheng-da any idea if there is any work-around or when this issue may get fixed?

**Comment by zheng-da** [comment]
We plan to have a v0.1.1 release. The estimated release time is around the end of May or beginning of June. Thanks.

**Comment by zheng-da** [comment]
For now, you might want to ensure the tensor for seed edges is int64. For some reason, it's int32 in windows.

**Comment by classicsong** [comment]
> thanks @zheng-da any idea if there is any work-around or when this issue may get fixed?

Can you try some linux environments? or use a 64bit virtual machine?

**Comment by rizwan29** [comment]
@zheng-da thanks, I have now changed the code to seed edges in int64. But now, I have encountered an another issue.

Logs are being recorded at: ckpts\TransE_l2_FB15k_17\train.log
Reading train triples....
Finished. Read 483142 train triples.
Reading valid triples....
Finished. Read 50000 valid triples.
Reading test triples....
Finished. Read 59071 test triples.
|Train|: 483142
random partition 483142 edges into 8 parts
part 0 has 60393 edges
part 1 has 60393 edges
part 2 has 60393 edges
part 3 has 60393 edges
part 4 has 60393 edges
part 5 has 60393 edges
part 6 has 60393 edges
part 7 has 60391 edges
|valid|: 50000
|test|: 59071
Total initialize time 3.847 seconds

Using backend: pytorch
C:\Users\riz\Anaconda3\lib\site-packages\dgl\base.py:25: UserWarning: multigraph will be deprecated.DGL will treat all graphs as multigraph in the future.
  warnings.warn(msg, warn_type)
Traceback (most recent call last):
  File "C:\Users\riz\Anaconda3\Scripts\dglke_train-script.py", line 11, in <module>
    load_entry_point('dglke==0.1.0.dev0', 'console_scripts', 'dglke_train')()
  File "C:\Users\riz\Anaconda3\lib\site-packages\dglke-0.1.0.dev0-py3.7.egg\dglke\train.py", line 278, in main
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TransEScore.create_neg.<locals>.fn'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\riz\Anaconda3\lib\multiprocessing\spawn.py", line 120, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by classicsong** [comment]
> thanks @zheng-da any idea if there is any work-around or when this issue may get fixed?

Can you try install dgl-ke from source and change:
https://github.com/awslabs/dgl-ke/blob/cc64f716462dfc04990a0173fd97b8e33a08768b/python/dglke/dataloader/sampler.py#L360
to 

`seed_edges=F.tensor(self.edge_parts[rank], dtype=F.int64),`

**Comment by ChrisDelClea** [comment]
I ran into the same error. After i modifed the `sampler.py` i get the following error: 
```python
Expected type graph.Graph but get graph.HetroGraph
```
Why could that be and how to fix it? 

Best regards
Chris
